import { StyleSheet } from "@react-pdf/renderer";
import type { Locale } from "@/i18n/routing";
import { getPdfFontFamily, pdfUsesIndicScript } from "./fonts";

const NIGHT = "#050505";
const PAPER = "#F7F4EE";
const FIELD = "#E8E2D6";
const INK = "#11100E";
const MUTED = "#6E675E";
const BERRY = "#C43C2C";
const TEAL = "#1A6B73";
const GOLD = "#E8B84A";
const LINE = "#D6D0C4";
const LINE_NIGHT = "#2A2927";

export function createPdfStyles(locale: Locale = "en") {
  const fontFamily = getPdfFontFamily(locale);
  const indic = pdfUsesIndicScript(locale);
  const displayWeight = indic ? 700 : 500;
  const kickerSize = indic ? 8 : 8;
  const bodySize = indic ? 9.5 : 10;

  return StyleSheet.create({
    paperPage: {
      paddingTop: 36,
      paddingHorizontal: 36,
      paddingBottom: 64,
      fontSize: bodySize,
      fontFamily,
      backgroundColor: PAPER,
      color: INK,
    },
    coverPage: {
      paddingTop: 36,
      paddingHorizontal: 36,
      paddingBottom: 40,
      fontSize: bodySize,
      fontFamily,
      backgroundColor: NIGHT,
      color: PAPER,
    },
    page: {
      paddingTop: 36,
      paddingHorizontal: 36,
      paddingBottom: 64,
      fontSize: bodySize,
      fontFamily,
      backgroundColor: PAPER,
      color: INK,
    },
    profilePage: {
      paddingTop: 36,
      paddingHorizontal: 36,
      paddingBottom: 64,
      fontSize: bodySize,
      fontFamily,
      backgroundColor: PAPER,
      color: INK,
    },

    wordmarkTop: {
      fontSize: 8,
      letterSpacing: 3.2,
      fontWeight: displayWeight,
      color: INK,
      fontFamily,
    },
    wordmarkBot: {
      fontSize: 11,
      letterSpacing: 1.2,
      fontWeight: displayWeight,
      color: INK,
      fontFamily,
    },
    wordmarkTopInvert: {
      fontSize: 8,
      letterSpacing: 3.2,
      fontWeight: displayWeight,
      color: PAPER,
      fontFamily,
    },
    wordmarkBotInvert: {
      fontSize: 11,
      letterSpacing: 1.2,
      fontWeight: displayWeight,
      color: PAPER,
      fontFamily,
    },
    wordmarkRow: {
      flexDirection: "row",
      alignItems: "center",
      marginTop: 3,
    },
    dot: {
      width: 5,
      height: 5,
      borderRadius: 3,
      backgroundColor: INK,
      marginRight: 6,
    },
    dotInvert: {
      width: 5,
      height: 5,
      borderRadius: 3,
      backgroundColor: PAPER,
      marginRight: 6,
    },

    coverTop: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "flex-start",
      marginBottom: 28,
    },
    coverKickerRow: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "flex-end",
      marginBottom: 10,
      paddingBottom: 10,
      borderBottomWidth: 0.75,
      borderBottomColor: LINE_NIGHT,
    },
    kicker: {
      fontSize: kickerSize,
      letterSpacing: indic ? 0.6 : 2.2,
      textTransform: indic ? "none" : "uppercase",
      color: MUTED,
      fontFamily,
    },
    kickerInvert: {
      fontSize: kickerSize,
      letterSpacing: indic ? 0.6 : 2.2,
      textTransform: indic ? "none" : "uppercase",
      color: "#9A948A",
      fontFamily,
    },
    kickerBerry: { color: BERRY },
    kickerTeal: { color: TEAL },
    kickerGold: { color: GOLD },
    sectionNum: {
      fontSize: 10,
      letterSpacing: 1.6,
      color: MUTED,
      fontFamily,
    },
    sectionNumInvert: {
      fontSize: 10,
      letterSpacing: 1.6,
      color: "#9A948A",
      fontFamily,
    },
    coverName: {
      fontSize: indic ? 26 : 34,
      lineHeight: 1.12,
      fontWeight: displayWeight,
      letterSpacing: indic ? 0 : -0.8,
      color: PAPER,
      marginBottom: 14,
      fontFamily,
    },
    coverLead: {
      fontSize: indic ? 10 : 11,
      lineHeight: 1.5,
      color: "#C8C2B6",
      maxWidth: 420,
      marginBottom: 28,
      fontFamily,
    },
    coverGrid: {
      flexDirection: "row",
      borderWidth: 0.75,
      borderColor: LINE_NIGHT,
    },
    coverCell: {
      flex: 1,
      padding: 14,
      borderRightWidth: 0.75,
      borderRightColor: LINE_NIGHT,
    },
    coverCellLast: {
      flex: 1,
      padding: 14,
    },
    coverIndex: {
      fontSize: indic ? 28 : 36,
      fontWeight: displayWeight,
      color: BERRY,
      letterSpacing: -1,
      fontFamily,
    },
    coverMeta: {
      fontSize: indic ? 11 : 12,
      fontWeight: displayWeight,
      color: PAPER,
      marginTop: 4,
      fontFamily,
    },
    coverHint: {
      fontSize: 8,
      color: "#8A847A",
      marginTop: 8,
      lineHeight: 1.4,
      fontFamily,
    },

    sectionHead: {
      marginBottom: 16,
    },
    sectionHeadTop: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "flex-end",
      marginBottom: 8,
    },
    sectionTitle: {
      fontSize: indic ? 16 : 20,
      fontWeight: displayWeight,
      letterSpacing: indic ? 0 : -0.4,
      color: INK,
      marginBottom: 10,
      fontFamily,
    },
    hairline: {
      borderBottomWidth: 0.75,
      borderBottomColor: LINE,
    },

    grid2: {
      flexDirection: "row",
      flexWrap: "wrap",
      borderWidth: 0.75,
      borderColor: LINE,
      marginBottom: 14,
    },
    cell: {
      width: "50%",
      padding: 12,
      borderRightWidth: 0.75,
      borderRightColor: LINE,
      borderBottomWidth: 0.75,
      borderBottomColor: LINE,
    },
    cellLabel: {
      fontSize: indic ? 7 : 8,
      letterSpacing: indic ? 0.4 : 1.8,
      textTransform: indic ? "none" : "uppercase",
      color: MUTED,
      marginBottom: 6,
      fontFamily,
    },
    cellValue: {
      fontSize: indic ? 11 : 12,
      fontWeight: displayWeight,
      color: INK,
      fontFamily,
    },
    warningCell: {
      borderWidth: 0.75,
      borderColor: GOLD,
      backgroundColor: FIELD,
      padding: 10,
      marginBottom: 8,
    },
    warningText: {
      fontSize: indic ? 8.5 : 9,
      lineHeight: 1.45,
      color: INK,
      fontFamily,
    },
    medical: {
      borderWidth: 0.75,
      borderColor: BERRY,
      padding: 12,
      marginBottom: 12,
      backgroundColor: PAPER,
    },

    planRow: {
      flexDirection: "row",
      borderBottomWidth: 0.75,
      borderBottomColor: LINE,
      paddingVertical: 12,
      alignItems: "flex-start",
    },
    planImage: {
      width: 92,
      height: 70,
      objectFit: "cover",
      marginRight: 12,
      backgroundColor: FIELD,
    },
    foodImage: {
      width: 64,
      height: 64,
      objectFit: "cover",
      marginRight: 12,
      backgroundColor: FIELD,
    },
    planNum: {
      fontSize: 8,
      letterSpacing: 1.4,
      color: MUTED,
      marginBottom: 3,
      fontFamily,
    },
    planTitle: {
      fontSize: indic ? 11 : 12,
      fontWeight: displayWeight,
      color: INK,
      marginBottom: 4,
      fontFamily,
    },
    step: {
      fontSize: indic ? 8.5 : 9,
      lineHeight: 1.4,
      color: "#3A372F",
      marginBottom: 2,
      fontFamily,
    },
    muted: {
      fontSize: 8,
      color: MUTED,
      marginTop: 4,
      fontFamily,
    },
    body: {
      fontSize: bodySize,
      lineHeight: 1.5,
      marginBottom: 8,
      color: "#3A372F",
      fontFamily,
    },

    h1: {
      fontSize: indic ? 16 : 20,
      color: INK,
      marginBottom: 12,
      marginTop: 8,
      fontWeight: displayWeight,
      fontFamily,
    },
    h2: {
      fontSize: indic ? 11 : 12,
      color: INK,
      marginBottom: 8,
      marginTop: 4,
      fontWeight: displayWeight,
      fontFamily,
    },
    coverTitle: {
      fontSize: indic ? 26 : 34,
      color: PAPER,
      marginBottom: 8,
      fontWeight: displayWeight,
      fontFamily,
    },
    coverSub: {
      fontSize: 12,
      color: "#C8C2B6",
      marginBottom: 24,
      fontFamily,
    },
    card: {
      marginBottom: 0,
      paddingVertical: 12,
      borderBottomWidth: 0.75,
      borderBottomColor: LINE,
    },
    cardImage: {
      width: 160,
      height: 96,
      objectFit: "cover",
      marginBottom: 8,
      backgroundColor: FIELD,
    },
    row: {
      flexDirection: "row",
      marginBottom: 0,
      alignItems: "flex-start",
      borderBottomWidth: 0.75,
      borderBottomColor: LINE,
      paddingVertical: 10,
    },

    pdfSectionTitle: {
      fontSize: indic ? 11 : 12,
      color: INK,
      fontWeight: displayWeight,
      marginBottom: 8,
      marginTop: 4,
      fontFamily,
    },
    pdfWarning: {
      fontSize: indic ? 8 : 8.5,
      color: INK,
      marginBottom: 12,
      marginTop: 4,
      borderWidth: 0.75,
      borderColor: GOLD,
      backgroundColor: FIELD,
      padding: 8,
      fontFamily,
    },
    tableHeadRow: {
      flexDirection: "row",
      borderTopWidth: 0.75,
      borderBottomWidth: 0.75,
      borderColor: LINE,
      paddingVertical: 6,
      paddingHorizontal: 4,
      backgroundColor: FIELD,
    },
    tableHeadCell: {
      flex: 1,
      fontSize: indic ? 6.5 : 7,
      color: MUTED,
      letterSpacing: indic ? 0.2 : 1.1,
      textTransform: indic ? "none" : "uppercase",
      fontFamily,
    },
    tableRow: {
      flexDirection: "row",
      borderBottomWidth: 0.5,
      borderBottomColor: LINE,
      paddingVertical: 5,
      paddingHorizontal: 4,
    },
    tableCell: {
      flex: 1,
      fontSize: indic ? 7 : 7.5,
      color: "#3A372F",
      lineHeight: 1.4,
      fontFamily,
    },
    profileHeader: { marginBottom: 18 },
    profileBrand: {
      fontSize: 11,
      color: INK,
      fontWeight: displayWeight,
      marginBottom: 4,
      fontFamily,
    },
    profileTitle: {
      fontSize: indic ? 16 : 20,
      color: INK,
      fontWeight: displayWeight,
      fontFamily,
    },
    profileGrid: {
      flexDirection: "row",
      flexWrap: "wrap",
      borderWidth: 0.75,
      borderColor: LINE,
      marginBottom: 12,
    },
    profileCell: {
      width: "50%",
      padding: 12,
      borderRightWidth: 0.75,
      borderRightColor: LINE,
      borderBottomWidth: 0.75,
      borderBottomColor: LINE,
    },
    profileLabel: {
      fontSize: indic ? 7 : 8,
      color: MUTED,
      letterSpacing: indic ? 0.4 : 1.8,
      textTransform: indic ? "none" : "uppercase",
      marginBottom: 6,
      fontFamily,
    },
    profileValue: {
      fontSize: indic ? 11 : 12,
      color: INK,
      fontWeight: displayWeight,
      fontFamily,
    },
    profileWarning: {
      borderWidth: 0.75,
      borderColor: GOLD,
      backgroundColor: FIELD,
      padding: 10,
      marginBottom: 8,
    },
    profileWarningText: {
      fontSize: indic ? 8.5 : 9,
      color: INK,
      lineHeight: 1.45,
      fontFamily,
    },
    profileDivider: {
      marginTop: 16,
      marginBottom: 12,
      borderBottomWidth: 0.75,
      borderBottomColor: LINE,
    },
    profileGuideLead: {
      fontSize: indic ? 14 : 16,
      color: INK,
      fontWeight: displayWeight,
      marginBottom: 6,
      fontFamily,
    },

    trackerHabit: {
      borderBottomWidth: 0.75,
      borderBottomColor: LINE,
      paddingVertical: 8,
      flexDirection: "row",
      alignItems: "center",
    },
    trackerLabel: {
      fontSize: indic ? 9 : 10,
      fontWeight: displayWeight,
      color: INK,
      marginBottom: 2,
      fontFamily,
    },
    trackerHow: {
      fontSize: indic ? 7.5 : 8,
      lineHeight: 1.35,
      color: MUTED,
      fontFamily,
    },
    trackerWeekRow: {
      flexDirection: "row",
      alignItems: "center",
    },
    trackerWeek: {
      width: 32,
      fontSize: 7,
      color: MUTED,
      textAlign: "center",
      fontFamily,
    },
    trackerCol: {
      width: 32,
      alignItems: "center",
      justifyContent: "center",
    },
    trackerNameCol: {
      flex: 1,
      paddingRight: 10,
    },
    trackerHeadRow: {
      flexDirection: "row",
      alignItems: "center",
      borderBottomWidth: 0.75,
      borderBottomColor: LINE,
      paddingBottom: 6,
      marginBottom: 2,
    },
    check: {
      width: 11,
      height: 11,
      borderWidth: 0.75,
      borderColor: INK,
    },

    watermark: {
      position: "absolute",
      top: "38%",
      left: "8%",
      fontSize: 42,
      color: BERRY,
      opacity: 0.12,
      letterSpacing: 6,
      transform: "rotate(-28deg)",
      fontFamily,
    },
    pageFooter: {
      position: "absolute",
      bottom: 20,
      left: 36,
      right: 36,
    },
    footerRule: {
      borderBottomWidth: 0.75,
      borderBottomColor: LINE,
      marginBottom: 8,
    },
    footerRow: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      marginBottom: 4,
    },
    footerBrand: {
      fontSize: 7,
      letterSpacing: 1.8,
      color: MUTED,
      fontFamily,
    },
    footerPage: {
      fontSize: 8,
      color: MUTED,
      fontFamily,
    },
    footerDisclaimer: {
      fontSize: 6.5,
      lineHeight: 1.35,
      color: MUTED,
      fontFamily,
    },
    footer: {
      position: "absolute",
      bottom: 30,
      left: 36,
      right: 36,
      fontSize: 7,
      color: MUTED,
      textAlign: "center",
      fontFamily,
    },
    trackerBox: {
      borderWidth: 0.75,
      borderColor: LINE,
      padding: 8,
      marginBottom: 6,
      fontSize: 9,
    },
  });
}

/** @deprecated Use createPdfStyles(locale) */
export const pdfStyles = createPdfStyles("en");

export type PdfStyles = ReturnType<typeof createPdfStyles>;
