import { StyleSheet } from "@react-pdf/renderer";

export const pdfStyles = StyleSheet.create({
  page: {
    padding: 40,
    fontSize: 11,
    fontFamily: "Helvetica",
    color: "#0f172a",
  },
  coverTitle: {
    fontSize: 28,
    color: "#f23838",
    marginBottom: 8,
    fontWeight: "bold",
  },
  coverSub: { fontSize: 14, color: "#130101", marginBottom: 24 },
  h1: {
    fontSize: 18,
    color: "#f23838",
    marginBottom: 12,
    marginTop: 8,
    fontWeight: "bold",
  },
  h2: {
    fontSize: 14,
    color: "#1a7a7a",
    marginBottom: 8,
    marginTop: 12,
    fontWeight: "bold",
  },
  body: { fontSize: 11, lineHeight: 1.5, marginBottom: 8, color: "#334155" },
  muted: { fontSize: 9, color: "#64748b", marginTop: 4 },
  card: {
    marginBottom: 16,
    padding: 12,
    borderWidth: 1,
    borderColor: "#e2e8f0",
    borderRadius: 4,
  },
  cardImage: { width: 200, height: 120, objectFit: "cover", marginBottom: 8 },
  foodImage: { width: 80, height: 80, objectFit: "cover", marginRight: 12 },
  row: { flexDirection: "row", marginBottom: 12, alignItems: "flex-start" },
  watermark: {
    position: "absolute",
    top: "40%",
    left: "10%",
    fontSize: 48,
    color: "#94a3b8",
    opacity: 0.25,
    transform: "rotate(-30deg)",
  },
  footer: {
    position: "absolute",
    bottom: 30,
    left: 40,
    right: 40,
    fontSize: 8,
    color: "#64748b",
    textAlign: "center",
  },
  trackerBox: {
    borderWidth: 1,
    borderColor: "#cbd5e1",
    padding: 8,
    marginBottom: 6,
    fontSize: 10,
  },
  medical: {
    backgroundColor: "#fde7e7",
    padding: 12,
    marginBottom: 12,
    borderLeftWidth: 4,
    borderLeftColor: "#f23838",
  },
});
